#!/usr/bin/env python
################################################################
#  This file part of GALA Gap-free Long-reads Assembler        #
#  Auther: Mohamed awad                                        #
#  Company: Xiangchao Gan lab (MPIPZ)                          #
#  Released under the (MIT) license (see LICENSE file)         #
################################################################
import os
a=['ccm','comp','mdm','newgenome','readsep','reformat','seprator','gala']
for i in a:
    b='/usr/bin/'
    c=''.join(list(open(i)))
    c=c.replace('path=os.getcwd()','path="'+b+'/bin"')
    d=open(b+i,'w')
    d.writelines(c)
    d.close()
    os.system('chmod +x '+b+i)
os.system('cp -RT src /usr/bin')

